language: node_js
node_js:
  - "16"
dist: trusty
sudo: required

branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
install:
  - npm install
script:
  - npm run build --prod --base-href turing-machine

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/turing-machine
  on:
    branch: master
