language: node_js
node_js:
  - "19.5.0"
dist: trusty
sudo: required

branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
install:
  - npm install
script:
  - ng lint
  - npm run test-headless
  - ng build --prod --base-href https://sitmcella.github.io/turing-machine/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/turing-machine
  on:
    branch: master
