name: Angular CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Adding Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: npm install and npm run CI commands
        run: |
          npm install -g @angular/cli
          npm i
          npm run build --prod -- --base-href="https://sitmcella.github.io/turing-machine/"
      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/your-angular-app
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
