name: Angular CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Adding Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: npm install and npm run CI commands
        run: |
          npm install -g @angular/cli
          npm i
          npm run build --prod -- --base-href="https://sitmcella.github.io/turing-machine/"
      - name: Deploy to gh pages
        run: |
          git remote set-url origin https://git:${GH_TOKEN}@github.com/sitMCella/turing-machine.git
          npx angular-cli-ghpages --dir=dist/turing-machine --no-silent --name="sitMCella" --email=phcella@libero.it
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
